#!/usr/bin/env python
import sys
import os
import argparse

parser = argparse.ArgumentParser(description='Mock realmd for acceptance testing')
parser.add_argument('command', help='command - must be `join` or `leave`')
parser.add_argument('domain', help='realm to join', nargs='?')
parser.add_argument('--computer-ou', help='Computer OU')
parser.add_argument('--name-only', help='print realm only (for use with `list`)', action='store_true')
parser.add_argument('-U', help='username')
args = parser.parse_args()

ACCEPT_USER     ='join_user'
ACCEPT_PASSWORD = 'topsecret'
KEYTAB_FILE     = '/etc/krb5.keytab'

status = 255

if args.command == "join":
    password = raw_input("fake password please: ")
    if password == ACCEPT_PASSWORD and args.U == ACCEPT_USER:
        print "OK: %s" % args.computer_ou
        with open(KEYTAB_FILE, 'w') as f:
            f.write(args.domain)
            status = 0
    else:
        print "bad password! username=%s password=%s" % (args.U, password)
elif args.command == "list":
    if os.path.isfile(KEYTAB_FILE):
        with open(KEYTAB_FILE, 'r') as f:
            print f.read()
            status = 0
elif args.command == "leave":
    if os.path.isfile(KEYTAB_FILE):
        print "leaving the domain..."
        os.remove(KEYTAB_FILE)
        status = 0
    else:
        # trying to leave a realm when not joined to one
        print "realm: Couldn't find a matching realm"
        status = 1
else:
    print "bad command for realm - want `join` or `leave` got :`%s`" % args.command
sys.exit(status)